name: CI
on: [pull_request, push]
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - uses: actions/cache@v3
        with:
          path: build
          key: build
      - run: cd src && yarn && yarn build  
  test-merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - uses: actions/cache@v3
        with:
          path: build
          key: build
      - run: cd tests && yarn && yarn test:merge
  test-oracle:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - uses: actions/cache@v3
        with:
          path: build
          key: build
      - run: cd tests && yarn && yarn test:oracle
  
